PROJECT_NAME: backend
PROJECT_ID: lavfehrxooahglpcucsh
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_120f15ac02a485295e4131a3f33bba56ac1fb250
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhdmZlaHJ4b29haGdscGN1Y3NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NzgwOTEsImV4cCI6MjA1MDQ1NDA5MX0.oNed5Ao0RS8WCrqY6gA43yemVtPnR1gdADYMJkK3ctE
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhdmZlaHJ4b29haGdscGN1Y3NoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNDg3ODA5MSwiZXhwIjoyMDUwNDU0MDkxfQ.s-RRb3VsfrwiPj8o63Gx7OtcSq91YS6-39ulXK7_SPU

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://lavfehrxooahglpcucsh.supabase.co

SERVER_HOST: 127.0.01
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
